#!/usr/bin/env bash
# Auto-detect monitors and generate Hyprland monitor configuration

MONITOR_LUA="$HOME/.config/hypr/monitors.lua"
HYPRPAPER_CONF="$HOME/.config/hypr/hyprpaper.conf"

echo "==> Detecting monitors..."

# Get all connected monitors
MONITORS=$(hyprctl monitors -j | jq -r '.[].name')

if [ -z "$MONITORS" ]; then
    echo "No monitors detected, using fallback configuration"
    cat > "$MONITOR_LUA" <<'EOF'
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})
EOF
    exit 0
fi

# Clear existing configuration
{
    echo "-- Auto-generated by ~/.config/hypr/scripts/detect-monitors.sh"
    echo "-- Run: bash ~/.config/hypr/scripts/detect-monitors.sh to regenerate"
    echo
} > "$MONITOR_LUA"

# Generate monitor configuration
MONITOR_COUNT=0
PRIMARY_MONITOR=""

for MONITOR in $MONITORS; do
    # Get preferred resolution and highest refresh rate
    MONITOR_INFO=$(hyprctl monitors -j | jq -r ".[] | select(.name==\"$MONITOR\")")
    WIDTH=$(echo "$MONITOR_INFO" | jq -r '.width')
    HEIGHT=$(echo "$MONITOR_INFO" | jq -r '.height')
    
    # Get available modes and find the highest refresh rate for current resolution
    MODES=$(hyprctl monitors -j | jq -r ".[] | select(.name==\"$MONITOR\") | .availableModes[]")
    
    # Extract refresh rates for current resolution
    REFRESH_RATES=$(echo "$MODES" | grep "^${WIDTH}x${HEIGHT}@" | sed 's/.*@\([0-9.]*\)Hz/\1/' | sort -rn)
    MAX_REFRESH=$(echo "$REFRESH_RATES" | head -n1)
    
    # If no matching resolution found, use current refresh rate
    if [ -z "$MAX_REFRESH" ]; then
        MAX_REFRESH=$(echo "$MONITOR_INFO" | jq -r '.refreshRate')
    fi
    
    # Round refresh rate to nearest integer
    REFRESH=$(printf "%.0f" "$MAX_REFRESH")
    
    # Position monitors side by side
    XPOS=$((MONITOR_COUNT * WIDTH))
    
    # First monitor is primary
    if [ $MONITOR_COUNT -eq 0 ]; then
        PRIMARY_MONITOR="$MONITOR"
    fi
    
    cat >> "$MONITOR_LUA" <<EOF
hl.monitor({
    output   = "$MONITOR",
    mode     = "${WIDTH}x${HEIGHT}@${REFRESH}",
    position = "${XPOS}x0",
    scale    = 1.0,
})

EOF
    echo "Configured: $MONITOR at ${WIDTH}x${HEIGHT}@${REFRESH}Hz (position: ${XPOS}x0)"

    MONITOR_COUNT=$((MONITOR_COUNT + 1))
done

echo "==> Generated $MONITOR_LUA with $MONITOR_COUNT monitor(s)"

# Update hyprpaper configuration with primary monitor
if [ -n "$PRIMARY_MONITOR" ]; then
    cat > "$HYPRPAPER_CONF" << EOF
wallpaper {
    monitor = $PRIMARY_MONITOR
    path = \$HOME/walls/wall1.png
    fit_mode = cover
}

splash = false
EOF
    echo "==> Updated hyprpaper.conf to use $PRIMARY_MONITOR"
fi
