-- Auto-generated by ~/.config/hypr/scripts/detect-monitors.sh
-- Run: bash ~/.config/hypr/scripts/detect-monitors.sh to regenerate

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@60",
    position = "0x0",
    scale    = 1.0,
})

